import { z } from 'zod';
import type { BiomeTerrainParams } from '@citygen/core';
import { Registry } from './registry.js';

/**
 * Biome packs: what the land does. Terrain and land cover consume the
 * `terrain` block; later stages read vegetation symbols, coast types and
 * agricultural patterns. See DESIGN §7.
 */
export const biomePackSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  terrain: z.object({
    id: z.string(),
    wetness: z.number().min(0).max(1),
    forestCover: z.number().min(0).max(1),
    forestKind: z.enum(['broadleaf', 'conifer', 'mixed', 'rainforest', 'none']),
    openKind: z.enum(['meadow', 'moor', 'steppe', 'savanna', 'scrub', 'desert']),
    treeLineM: z.number(),
    snowLineM: z.number(),
    coastKind: z.enum(['beach', 'cliff', 'marsh', 'mangrove']),
    farmland: z.number().min(0).max(1),
  }),
  fieldPattern: z.enum([
    'hedged',
    'openField',
    'fenced',
    'terraced',
    'irrigated',
    'oasis',
    'plantation',
    'paddy',
  ]),
  riverRegime: z.enum(['perennial', 'seasonal', 'braided']),
});
export type BiomePack = z.infer<typeof biomePackSchema>;

const packs: BiomePack[] = [
  {
    id: 'temperateMaritime',
    name: 'Temperate maritime',
    description:
      'Mild, wet, green: New England, the British Isles, Brittany, the Pacific Northwest lowlands.',
    terrain: {
      id: 'temperateMaritime',
      wetness: 0.75,
      forestCover: 0.45,
      forestKind: 'broadleaf',
      openKind: 'meadow',
      treeLineM: 700,
      snowLineM: 2500,
      coastKind: 'marsh',
      farmland: 0.6,
    },
    fieldPattern: 'hedged',
    riverRegime: 'perennial',
  },
  {
    id: 'temperateContinental',
    name: 'Temperate continental',
    description: 'Warm summers, cold winters: Central Europe, the American Midwest, Manchuria.',
    terrain: {
      id: 'temperateContinental',
      wetness: 0.55,
      forestCover: 0.4,
      forestKind: 'mixed',
      openKind: 'meadow',
      treeLineM: 1600,
      snowLineM: 2800,
      coastKind: 'beach',
      farmland: 0.7,
    },
    fieldPattern: 'openField',
    riverRegime: 'perennial',
  },
  {
    id: 'mediterranean',
    name: 'Mediterranean',
    description: 'Dry summers, wet winters: Iberia, Italy, Greece, the Levant coast, California.',
    terrain: {
      id: 'mediterranean',
      wetness: 0.35,
      forestCover: 0.25,
      forestKind: 'broadleaf',
      openKind: 'scrub',
      treeLineM: 1900,
      snowLineM: 3000,
      coastKind: 'cliff',
      farmland: 0.5,
    },
    fieldPattern: 'terraced',
    riverRegime: 'seasonal',
  },
  {
    id: 'boreal',
    name: 'Boreal',
    description: 'Long winters, conifer forest, many lakes: Scandinavia, Canada, Siberia.',
    terrain: {
      id: 'boreal',
      wetness: 0.85,
      forestCover: 0.75,
      forestKind: 'conifer',
      openKind: 'moor',
      treeLineM: 600,
      snowLineM: 1500,
      coastKind: 'cliff',
      farmland: 0.2,
    },
    fieldPattern: 'fenced',
    riverRegime: 'perennial',
  },
  {
    id: 'subarctic',
    name: 'Subarctic',
    description: 'Tundra and taiga edge: Lapland, Alaska, northern Russia.',
    terrain: {
      id: 'subarctic',
      wetness: 0.7,
      forestCover: 0.3,
      forestKind: 'conifer',
      openKind: 'moor',
      treeLineM: 300,
      snowLineM: 900,
      coastKind: 'cliff',
      farmland: 0.05,
    },
    fieldPattern: 'fenced',
    riverRegime: 'braided',
  },
  {
    id: 'steppe',
    name: 'Steppe',
    description: 'Semi-arid grassland: Ukraine, Kazakhstan, the Great Plains, the Pampas.',
    terrain: {
      id: 'steppe',
      wetness: 0.3,
      forestCover: 0.05,
      forestKind: 'broadleaf',
      openKind: 'steppe',
      treeLineM: 2500,
      snowLineM: 4000,
      coastKind: 'beach',
      farmland: 0.65,
    },
    fieldPattern: 'openField',
    riverRegime: 'seasonal',
  },
  {
    id: 'desert',
    name: 'Desert',
    description: 'Arid: Sahara, Arabia, the Atacama, the Mojave. Farming only by irrigation or oasis.',
    terrain: {
      id: 'desert',
      wetness: 0.08,
      forestCover: 0,
      forestKind: 'none',
      openKind: 'desert',
      treeLineM: 3000,
      snowLineM: 4500,
      coastKind: 'beach',
      farmland: 0.15,
    },
    fieldPattern: 'oasis',
    riverRegime: 'seasonal',
  },
  {
    id: 'semiArid',
    name: 'Semi-arid',
    description: 'Scrub and dry hills: the Maghreb interior, Anatolia, Australia’s wheat belt.',
    terrain: {
      id: 'semiArid',
      wetness: 0.2,
      forestCover: 0.1,
      forestKind: 'broadleaf',
      openKind: 'scrub',
      treeLineM: 2500,
      snowLineM: 4000,
      coastKind: 'beach',
      farmland: 0.35,
    },
    fieldPattern: 'irrigated',
    riverRegime: 'seasonal',
  },
  {
    id: 'subtropicalHumid',
    name: 'Subtropical humid',
    description: 'Hot wet summers: the American South, southern China, southern Brazil, Japan’s south.',
    terrain: {
      id: 'subtropicalHumid',
      wetness: 0.8,
      forestCover: 0.5,
      forestKind: 'mixed',
      openKind: 'meadow',
      treeLineM: 2200,
      snowLineM: 3800,
      coastKind: 'marsh',
      farmland: 0.6,
    },
    fieldPattern: 'paddy',
    riverRegime: 'perennial',
  },
  {
    id: 'tropicalMonsoon',
    name: 'Tropical monsoon',
    description: 'Wet and dry seasons: India, Indochina, West Africa’s coast.',
    terrain: {
      id: 'tropicalMonsoon',
      wetness: 0.9,
      forestCover: 0.45,
      forestKind: 'rainforest',
      openKind: 'savanna',
      treeLineM: 3200,
      snowLineM: 4800,
      coastKind: 'mangrove',
      farmland: 0.65,
    },
    fieldPattern: 'paddy',
    riverRegime: 'seasonal',
  },
  {
    id: 'tropicalRainforest',
    name: 'Tropical rainforest',
    description: 'Always wet: the Amazon, the Congo, Borneo.',
    terrain: {
      id: 'tropicalRainforest',
      wetness: 1,
      forestCover: 0.9,
      forestKind: 'rainforest',
      openKind: 'scrub',
      treeLineM: 3500,
      snowLineM: 5000,
      coastKind: 'mangrove',
      farmland: 0.2,
    },
    fieldPattern: 'plantation',
    riverRegime: 'perennial',
  },
  {
    id: 'savanna',
    name: 'Savanna',
    description: 'Grassland with scattered trees: East Africa, the Cerrado, northern Australia.',
    terrain: {
      id: 'savanna',
      wetness: 0.4,
      forestCover: 0.15,
      forestKind: 'broadleaf',
      openKind: 'savanna',
      treeLineM: 3000,
      snowLineM: 4800,
      coastKind: 'beach',
      farmland: 0.4,
    },
    fieldPattern: 'fenced',
    riverRegime: 'seasonal',
  },
  {
    id: 'alpine',
    name: 'Alpine',
    description: 'High mountains and valleys: the Alps, the Rockies, the Andes, the Himalaya foothills.',
    terrain: {
      id: 'alpine',
      wetness: 0.8,
      forestCover: 0.55,
      forestKind: 'conifer',
      openKind: 'meadow',
      treeLineM: 1900,
      snowLineM: 2700,
      coastKind: 'cliff',
      farmland: 0.3,
    },
    fieldPattern: 'fenced',
    riverRegime: 'braided',
  },
];

export const biomes = new Registry<BiomePack>('biome pack', biomePackSchema);
for (const p of packs) biomes.register(p);

/** Terrain parameters for a biome id, falling back to temperate maritime. */
export function biomeTerrain(id: string): BiomeTerrainParams {
  return (biomes.has(id) ? biomes.get(id) : biomes.get('temperateMaritime')).terrain;
}
