import { culturePackSchema, type CulturePack } from './schema.js';

/**
 * The first eight culture packs, chosen to span the world and the common
 * Call of Cthulhu settings. Name lists are generic words and common names;
 * grammars build settlement, street, district, water and business names.
 */

const enStreetSuffix = {
  artery: ['Street', 'Road', 'Avenue', 'High Street'],
  road: ['Road', 'Street', 'Avenue'],
  collector: ['Street', 'Avenue', 'Road'],
  street: ['Street', 'Lane', 'Row', 'Place'],
  lane: ['Lane', 'Alley', 'Court', 'Close', 'Yard'],
};

const raw: CulturePack[] = [
  {
    id: 'newEngland',
    name: 'New England',
    description: 'Colonial towns, mill towns and decaying ports of Massachusetts and Maine.',
    language: 'en',
    naming: {
      given: [
        'Abner',
        'Ezra',
        'Silas',
        'Obed',
        'Jeremiah',
        'Nathaniel',
        'Hiram',
        'Caleb',
        'Asenath',
        'Lavinia',
        'Prudence',
        'Mercy',
        'Abigail',
        'Hannah',
        'Eliza',
        'Sarah',
        'Walter',
        'Henry',
        'Ruth',
        'Edith',
        'Randolph',
        'Herbert',
        'Arthur',
        'Wilbur',
      ],
      family: [
        'Marsh',
        'Gilman',
        'Whateley',
        'Pickman',
        'Carter',
        'Ward',
        'Derby',
        'Peabody',
        'Orne',
        'Curwen',
        'Tillinghast',
        'Waite',
        'Eliot',
        'Sargent',
        'Hutchins',
        'Bishop',
        'Brewster',
        'Allen',
        'Phillips',
        'Upton',
        'Armitage',
        'Morgan',
        'Rice',
        'Dexter',
        'Hoadley',
        'Babson',
        'Wheeler',
        'Blake',
        'Peaslee',
        'Akeley',
      ],
      settlement: {
        patterns: ['{root}{suffix}', '{root} {landform}', 'New {old}', '{saint}'],
        parts: {
          root: [
            'Ark',
            'Inns',
            'Dun',
            'Kings',
            'Ayles',
            'Fox',
            'Bol',
            'Grey',
            'Miskaton',
            'Stur',
            'Salis',
            'Ded',
            'Glou',
            'Ips',
            'Rowl',
            'Marble',
            'Newbury',
            'Ames',
            'Wen',
            'Hal',
          ],
          suffix: ['ham', 'mouth', 'wich', 'port', 'bury', 'field', 'ton', 'ford', 'haven', 'ley'],
          landform: ['Harbor', 'Falls', 'Mills', 'Corners', 'Junction', 'Hollow', 'Neck', 'Point', 'Landing'],
          old: ['Bedford', 'Salem', 'Boston', 'Concord', 'Plymouth', 'Dover', 'Exeter', 'Braintree'],
          saint: ["Martin's Corner", 'Providence', 'Hope Valley', 'Peace Dale'],
        },
      },
      street: {
        patterns: [
          '{name} {suffix}',
          '{family} {suffix}',
          '{ordinal} {suffix}',
          '{tree} {suffix}',
          '{civic} {suffix}',
        ],
        parts: {
          name: [
            'Main',
            'Church',
            'Water',
            'High',
            'Pleasant',
            'Prospect',
            'Summer',
            'Winter',
            'Federal',
            'Union',
            'Washington',
            'Franklin',
            'Garrison',
            'Boundary',
            'Powder House',
            'Meeting House',
            'Derby',
            'Front',
            'Wharf',
            'Mill',
            'Bridge',
            'Beacon',
            'Hill',
            'River',
            'Salem',
            'Boston',
            'College',
            'Hangman',
            'Whipple',
            'Fish',
          ],
          ordinal: ['First', 'Second', 'Third', 'Fourth', 'Fifth', 'Sixth', 'Seventh', 'Eighth'],
          tree: [
            'Elm',
            'Maple',
            'Chestnut',
            'Walnut',
            'Cedar',
            'Pine',
            'Oak',
            'Birch',
            'Willow',
            'Spruce',
            'Hawthorn',
          ],
          civic: [
            'School',
            'Market',
            'Court',
            'Custom House',
            'Depot',
            'Cemetery',
            'Almshouse',
            'Armory',
            'Common',
          ],
        },
      },
      streetSuffix: enStreetSuffix,
      district: {
        patterns: [
          '{dir} End',
          '{family}town',
          '{feature} Hill',
          'The {feature}',
          '{feature} Point',
          '{dir} Side',
        ],
        parts: {
          dir: ['North', 'South', 'East', 'West'],
          feature: [
            'Beacon',
            'Copp',
            'Gallows',
            'Powder',
            'Mill',
            'Meeting',
            'Tannery',
            'Rope',
            'Fish',
            'Poverty',
            'Nob',
            'Federal',
            'Back Bay',
            'Fort',
            'Salt',
          ],
        },
      },
      water: {
        patterns: ['{name} River', '{name} Brook', '{family} Pond', '{name} Creek'],
        parts: {
          name: [
            'Miskatonic',
            'Manuxet',
            'Black',
            'Stony',
            'Mill',
            'Merrimack',
            'Charles',
            'Dead',
            'Salt',
            'Cold',
            'Otter',
            'Bear',
          ],
        },
      },
      business: {
        patterns: [
          "{family}'s {trade}",
          '{family} & Sons {trade}',
          '{family} Brothers',
          'The {adj} {trade}',
          '{family} {trade} Co.',
        ],
        parts: { adj: ['Old', 'Golden', 'Blue', 'Harbor', 'Colonial', 'Bay State', 'Pilgrim', 'Federal'] },
      },
      quarters: {
        core: 'Old Town',
        cathedral: 'Church Hill',
        castle: 'Fort Hill',
        market: 'Market Square',
        port: 'Waterfront',
        fishing: "Fishermen's Wharf",
        industrial: 'The Works',
        station: 'Depot Square',
      },
    },
    conventions: {
      earlyPattern: 'organic',
      modernFrom: 1780,
      blockSizeScale: 1.15,
      streetcarReach: 1.6,
      buildingKinds: {
        house: 'clapboard house',
        townhouse: 'brick townhouse',
        mansion: 'sea-captain’s mansion',
        shophouse: 'store with rooms above',
        shack: 'shanty',
        keep: 'blockhouse',
        cathedral: 'meeting house',
        rowhouse: 'brick row house',
        tenement: 'triple-decker',
        shop: 'storefront',
        office: 'office block',
        villa: 'Queen Anne villa',
        apartment: 'apartment house',
        tower: 'apartment tower',
        warehouse: 'brick warehouse',
        workshop: 'workshop',
      },
      religious: [
        'Congregational church',
        'Episcopal church',
        'Baptist church',
        'Catholic church',
        'Unitarian church',
        'Esoteric Order hall',
      ],
      civic: [
        'town hall',
        'custom house',
        'library',
        'grange hall',
        'fire house',
        'post office',
        'courthouse',
        'historical society',
      ],
      materials: {
        preIndustrial: { timber: 8, brick: 1, stone: 1 },
        industrial: { timber: 5, brick: 4, stone: 1 },
        modern: { timber: 3, brick: 3, concrete: 3, steel: 1 },
      },
      transport: { rail: 1835, tram: 1888, motorway: 1956, container: 1966 },
      walls: false,
    },
  },
  {
    id: 'england',
    name: 'England',
    description: 'Market towns, cathedral cities and industrial boroughs.',
    language: 'en',
    naming: {
      given: [
        'Alfred',
        'Edmund',
        'Harold',
        'Cuthbert',
        'Percival',
        'Reginald',
        'Wilfred',
        'Ernest',
        'Agnes',
        'Beatrice',
        'Dorothy',
        'Edith',
        'Florence',
        'Gladys',
        'Mabel',
        'Winifred',
        'George',
        'Albert',
        'Thomas',
        'William',
        'Mary',
        'Elsie',
        'Violet',
        'Ivy',
      ],
      family: [
        'Ashcroft',
        'Blackwood',
        'Carrow',
        'Dunstan',
        'Fenwick',
        'Grimshaw',
        'Hargreaves',
        'Illingworth',
        'Jessop',
        'Kettering',
        'Longbottom',
        'Mortlake',
        'Norrington',
        'Oakes',
        'Pemberton',
        'Quennell',
        'Ravenscroft',
        'Shuttleworth',
        'Thorne',
        'Underhill',
        'Verney',
        'Whitcombe',
        'Yeoman',
        'Pargeter',
        'Sowerby',
        'Tremlett',
        'Frobisher',
        'Marchbanks',
        'Cholmondeley',
        'Wetherby',
      ],
      settlement: {
        patterns: [
          '{root}{suffix}',
          '{root}{suffix}-on-{river}',
          '{prefix} {root}{suffix}',
          '{root}{suffix} {feature}',
        ],
        parts: {
          root: [
            'Ash',
            'Brack',
            'Chel',
            'Dun',
            'Ex',
            'Farn',
            'Gre',
            'Hal',
            'Kir',
            'Lit',
            'Mal',
            'Nor',
            'Ox',
            'Pen',
            'Ros',
            'Salt',
            'Thorn',
            'Wal',
            'Wig',
            'Yar',
            'Bram',
            'Crox',
            'Hen',
            'Stam',
          ],
          suffix: [
            'ford',
            'bury',
            'ham',
            'ton',
            'wick',
            'by',
            'mouth',
            'chester',
            'minster',
            'thorpe',
            'ley',
            'field',
            'worth',
            'stoke',
            'bridge',
            'combe',
          ],
          river: ['Sea', 'Trent', 'Avon', 'Wye', 'Ouse', 'Derwent', 'Tyne'],
          prefix: ['Great', 'Little', 'Market', 'Bishop’s', 'King’s', 'Long', 'Nether', 'Upper'],
          feature: ['Regis', 'Magna', 'Parva', 'Abbas', 'Episcopi'],
        },
      },
      street: {
        patterns: [
          '{name} {suffix}',
          '{family} {suffix}',
          '{trade}gate',
          '{saint} {suffix}',
          'The {feature}',
        ],
        parts: {
          name: [
            'High',
            'Church',
            'Mill',
            'Bridge',
            'Castle',
            'Market',
            'Station',
            'Victoria',
            'Albert',
            'Queen',
            'King',
            'Prince',
            'Chapel',
            'Priory',
            'Abbey',
            'Friar',
            'Bull',
            'Sheep',
            'Swan',
            'Cross',
            'Coronation',
            'Jubilee',
            'Wellington',
            'Nelson',
            'Gas',
            'Foundry',
            'Canal',
            'Wharf',
            'Bath',
            'Broad',
            'North',
            'South',
            'East',
            'West',
          ],
          trade: ['Fish', 'Cheap', 'Skinner', 'Wool', 'Salt', 'Coal', 'Iron', 'Silver', 'Corn', 'Butter'],
          saint: [
            "St Mary's",
            "St Peter's",
            "St Michael's",
            "St Giles'",
            "St Botolph's",
            "St Anne's",
            'All Saints',
          ],
          feature: [
            'Shambles',
            'Butts',
            'Green',
            'Tything',
            'Crescent',
            'Parade',
            'Grove',
            'Mount',
            'Walk',
            'Pantiles',
          ],
        },
      },
      streetSuffix: {
        ...enStreetSuffix,
        street: ['Street', 'Lane', 'Row', 'Terrace', 'Place'],
        lane: ['Lane', 'Alley', 'Yard', 'Passage', 'Mews', 'Close'],
      },
      district: {
        patterns: ['{feature}', '{family} Park', '{dir} {feature}', 'The {feature}', '{name}gate'],
        parts: {
          dir: ['North', 'South', 'East', 'West', 'Upper', 'Lower'],
          feature: [
            'Moor',
            'Fields',
            'Common',
            'Marsh',
            'Hill',
            'Cross',
            'Heath',
            'Green',
            'Bank',
            'Quays',
            'Grange',
            'Rise',
            'Vale',
            'Terrace',
          ],
          name: ['Micklegate', 'Newgate', 'Eastgate', 'Westgate', 'Northgate', 'Southgate', 'Coppergate'],
        },
      },
      water: {
        patterns: ['River {name}', '{name} Brook', '{name} Beck', '{name} Water'],
        parts: {
          name: [
            'Wye',
            'Derwent',
            'Calder',
            'Lune',
            'Kennet',
            'Stour',
            'Tame',
            'Hodder',
            'Wharfe',
            'Blackwater',
            'Eden',
            'Tern',
          ],
        },
      },
      business: {
        patterns: [
          '{family} & {family2}',
          "{family}'s {trade}",
          '{family} Bros. {trade}',
          'The {adj} {trade}',
          '{family} & Son',
        ],
        parts: {
          adj: ['Royal', 'Crown', 'Old', 'Golden', 'Victoria', 'Imperial', 'County', 'Borough'],
          family2: ['Sons', 'Co.', 'Daughters', 'Partners', 'Nephew'],
        },
      },
      quarters: {
        core: 'Old Town',
        cathedral: 'Cathedral Close',
        castle: 'Castle Ward',
        market: 'Market Place',
        port: 'The Docks',
        fishing: 'Fishergate',
        industrial: 'The Works',
        station: 'Station Approach',
      },
    },
    conventions: {
      earlyPattern: 'organic',
      modernFrom: 1780,
      blockSizeScale: 1,
      streetcarReach: 1.1,
      buildingKinds: {
        house: 'terraced house',
        townhouse: 'town house',
        mansion: 'villa',
        shophouse: 'shop with flat above',
        shack: 'back-to-back',
        keep: 'keep',
        cathedral: 'minster',
        rowhouse: 'terrace',
        tenement: 'back-to-back',
        shop: 'shop',
        office: 'office block',
        villa: 'villa',
        apartment: 'mansion flats',
        tower: 'tower block',
        warehouse: 'warehouse',
        workshop: 'works',
      },
      religious: [
        'parish church',
        'Methodist chapel',
        'Baptist chapel',
        'Catholic church',
        'synagogue',
        'Quaker meeting house',
      ],
      civic: [
        'town hall',
        'guildhall',
        'corn exchange',
        'workhouse',
        'police station',
        'public library',
        'assembly rooms',
        'mechanics’ institute',
      ],
      materials: {
        preIndustrial: { timber: 4, stone: 4, brick: 3 },
        industrial: { brick: 8, stone: 3, timber: 1 },
        modern: { brick: 5, concrete: 4, steel: 1, stone: 1 },
      },
      transport: { rail: 1830, tram: 1885, motorway: 1959, container: 1968 },
      walls: true,
    },
  },
  {
    id: 'france',
    name: 'France',
    description: 'Bastides, cathedral towns, Haussmann boulevards and Atlantic ports.',
    language: 'fr',
    naming: {
      given: [
        'Jean',
        'Pierre',
        'Louis',
        'Henri',
        'Marcel',
        'Émile',
        'Gaston',
        'Lucien',
        'Marie',
        'Jeanne',
        'Louise',
        'Marguerite',
        'Yvonne',
        'Odette',
        'Suzanne',
        'Germaine',
        'Auguste',
        'Armand',
        'Blanche',
        'Colette',
        'René',
        'Paul',
        'Simone',
        'Antoine',
      ],
      family: [
        'Lefebvre',
        'Moreau',
        'Girard',
        'Dubois',
        'Fontaine',
        'Lambert',
        'Rousseau',
        'Vincent',
        'Chevalier',
        'Garnier',
        'Faure',
        'Mercier',
        'Blanchard',
        'Perrin',
        'Bertrand',
        'Marchand',
        'Delacroix',
        'Renard',
        'Barbier',
        'Leclerc',
        'Boucher',
        'Aubert',
        'Charpentier',
        'Vidal',
        'Roux',
        'Guérin',
        'Picard',
        'Lemoine',
        'Gauthier',
        'Bonnet',
      ],
      settlement: {
        patterns: [
          '{root}{suffix}',
          'Saint-{saint}',
          '{root}{suffix}-sur-{river}',
          'Ville{suffix2}',
          'Le {noun}',
        ],
        parts: {
          root: [
            'Beau',
            'Clair',
            'Mont',
            'Val',
            'Roche',
            'Chât',
            'Ver',
            'Bel',
            'Font',
            'Aube',
            'Marc',
            'Sar',
            'Lor',
            'Bré',
            'Mor',
          ],
          suffix: [
            'mont',
            'ville',
            'court',
            'lieu',
            'fort',
            'vaux',
            'ac',
            'ay',
            'euil',
            'bourg',
            'ac',
            'gny',
          ],
          suffix2: ['neuve', 'franche', 'dieu', 'juif', 'longue'],
          saint: [
            'Malo',
            'Nazaire',
            'Étienne',
            'Denis',
            'Rémy',
            'Germain',
            'Jean-de-Luz',
            'Omer',
            'Quentin',
            'Brieuc',
          ],
          river: ['Loire', 'Mer', 'Seine', 'Marne', 'Orne', 'Vire'],
          noun: ['Havre', 'Mans', 'Puy', 'Croisic', 'Tréport', 'Palais'],
        },
      },
      street: {
        patterns: [
          'Rue {de} {name}',
          'Rue {family}',
          'Rue de la {feature}',
          '{suffix} {de} {name}',
          'Place {de} {name}',
          'Impasse {de} {feature}',
        ],
        parts: {
          de: ['de', 'du', 'des', 'de la'],
          name: [
            'la République',
            'la Gare',
            'l’Église',
            'la Paix',
            'Verdun',
            'Strasbourg',
            'Victor Hugo',
            'Pasteur',
            'Jean Jaurès',
            'Gambetta',
            'la Liberté',
            'Saint-Jacques',
            'Saint-Michel',
            'Notre-Dame',
            'la Halle',
            'Port',
            'la Fontaine',
            'Carnot',
            'Foch',
            'Clemenceau',
            '11 Novembre',
            'Général Leclerc',
            'Marché',
            'Moulins',
            'Remparts',
          ],
          feature: [
            'Halle',
            'Poste',
            'Mairie',
            'Forge',
            'Tannerie',
            'Vieille Poste',
            'Poterne',
            'Grande Fontaine',
            'Cordonnerie',
            'Boucherie',
            'Bourse',
            'Douane',
          ],
        },
      },
      streetSuffix: {
        artery: ['Avenue', 'Boulevard', 'Cours'],
        road: ['Route', 'Avenue', 'Chemin'],
        collector: ['Rue', 'Avenue'],
        street: ['Rue', 'Rue', 'Place'],
        lane: ['Impasse', 'Ruelle', 'Passage', 'Venelle'],
      },
      district: {
        patterns: ['Quartier {de} {feature}', 'Faubourg {de} {feature}', 'Les {plural}', 'Le {feature}'],
        parts: {
          de: ['de la', 'du', 'des', 'Saint-'],
          feature: [
            'Gare',
            'Halles',
            'Port',
            'Cathédrale',
            'Château',
            'Marché',
            'Moulins',
            'Jardins',
            'Fontaine',
            'Tanneurs',
            'Cordeliers',
            'Capucins',
            'Carmes',
            'Jacobins',
            'Roch',
            'Pierre',
          ],
          plural: [
            'Halles',
            'Chartrons',
            'Sablons',
            'Ormeaux',
            'Tilleuls',
            'Minimes',
            'Docks',
            'Batignolles',
          ],
        },
      },
      water: {
        patterns: ['La {name}', 'Le {name2}', 'Ruisseau {de} {name3}'],
        parts: {
          name: ['Vézère', 'Sèvre', 'Orne', 'Vilaine', 'Rance', 'Sarthe', 'Aulne'],
          name2: ['Loir', 'Lot', 'Tarn', 'Cher', 'Thouet'],
          de: ['de', 'des', 'du'],
          name3: ['Moulin', 'Fontaines', 'Pré', 'Bois'],
        },
      },
      business: {
        patterns: [
          'Maison {family}',
          '{family} & Fils',
          'Café {de} {name}',
          'Au {adj} {trade}',
          '{trade} {family}',
          'Hôtel {de} {name}',
        ],
        parts: {
          de: ['de la', 'du', 'des'],
          name: ['Commerce', 'Gare', 'Port', 'Paix', 'Poste', 'Marché', 'Univers', 'France'],
          adj: ['Bon', 'Vieux', 'Petit', 'Grand', 'Bel'],
        },
      },
      quarters: {
        core: 'Vieille Ville',
        cathedral: 'Quartier de la Cathédrale',
        castle: 'Quartier du Château',
        market: 'Les Halles',
        port: 'Quartier du Port',
        fishing: 'Quartier des Pêcheurs',
        industrial: 'Zone des Usines',
        station: 'Quartier de la Gare',
      },
    },
    conventions: {
      earlyPattern: 'organic',
      modernFrom: 1850,
      blockSizeScale: 0.95,
      streetcarReach: 0.7,
      buildingKinds: {
        house: 'maison',
        townhouse: 'hôtel particulier',
        mansion: 'château',
        shophouse: 'immeuble with shop',
        shack: 'masure',
        keep: 'donjon',
        cathedral: 'cathédrale',
        rowhouse: 'maison de ville',
        tenement: 'immeuble de rapport',
        shop: 'boutique',
        office: 'immeuble de bureaux',
        villa: 'villa',
        apartment: 'immeuble',
        tower: 'tour',
        warehouse: 'entrepôt',
        workshop: 'atelier',
      },
      religious: ['église', 'chapelle', 'couvent', 'temple protestant', 'synagogue'],
      civic: [
        'mairie',
        'hôtel de ville',
        'halle',
        'préfecture',
        'gendarmerie',
        'bureau de poste',
        'école communale',
        'tribunal',
        'lavoir',
      ],
      materials: {
        preIndustrial: { stone: 7, timber: 3, brick: 1 },
        industrial: { stone: 5, brick: 4, timber: 1 },
        modern: { stone: 3, concrete: 5, brick: 2 },
      },
      transport: { rail: 1840, tram: 1890, motorway: 1960, container: 1968 },
      walls: true,
    },
  },
  {
    id: 'germanyCentralEurope',
    name: 'Germany and Central Europe',
    description: 'Walled Altstädte, Gründerzeit rings and Ruhr industry.',
    language: 'de',
    naming: {
      given: [
        'Friedrich',
        'Heinrich',
        'Wilhelm',
        'Otto',
        'Karl',
        'Ernst',
        'Hermann',
        'Gustav',
        'Anna',
        'Emma',
        'Gertrud',
        'Hedwig',
        'Klara',
        'Margarethe',
        'Elisabeth',
        'Frieda',
        'Johann',
        'Max',
        'Kurt',
        'Walther',
        'Erna',
        'Ida',
        'Luise',
        'Martha',
      ],
      family: [
        'Bauer',
        'Schäfer',
        'Hoffmann',
        'Krüger',
        'Vogt',
        'Brandt',
        'Ziegler',
        'Kessler',
        'Lindner',
        'Winkler',
        'Pfeiffer',
        'Baumgartner',
        'Thalberg',
        'Eisenreich',
        'Wendland',
        'Steinmetz',
        'Reinhardt',
        'Sauer',
        'Ackermann',
        'Fuchs',
        'Kunz',
        'Voss',
        'Behrens',
        'Nussbaum',
        'Habermann',
        'Gerlach',
        'Zimmermann',
        'Ostermann',
        'Böhm',
        'Falkenrath',
      ],
      settlement: {
        patterns: ['{root}{suffix}', '{prefix}{root}{suffix}', '{root}{suffix} am {river}', 'Sankt {saint}'],
        parts: {
          root: [
            'Wolf',
            'Stein',
            'Berg',
            'Wald',
            'Rothen',
            'Alten',
            'Neu',
            'Friedrichs',
            'Hohen',
            'Kirch',
            'Mühl',
            'Salz',
            'Eisen',
            'Schön',
            'Wester',
            'Ober',
            'Hammel',
            'Linden',
            'Königs',
            'Bad ',
          ],
          suffix: [
            'burg',
            'berg',
            'hausen',
            'heim',
            'dorf',
            'stadt',
            'furt',
            'bach',
            'feld',
            'stein',
            'brück',
            'walde',
            'ingen',
            'thal',
          ],
          prefix: ['Ober', 'Unter', 'Groß', 'Klein', 'Alt', 'Neu'],
          river: ['Main', 'Rhein', 'Elbe', 'Oder', 'Neckar', 'Inn', 'Weser'],
          saint: ['Goar', 'Wendel', 'Blasien', 'Gallen', 'Veit'],
        },
      },
      street: {
        patterns: [
          '{name}{suffix}',
          '{family}{suffix}',
          'Am {feature}',
          'An der {feature2}',
          '{saint}{suffix}',
        ],
        parts: {
          name: [
            'Haupt',
            'Bahnhof',
            'Kirch',
            'Markt',
            'Schloss',
            'Mühlen',
            'Berg',
            'Brücken',
            'Schul',
            'Garten',
            'Linden',
            'Ring',
            'Kaiser',
            'König',
            'Bismarck',
            'Goethe',
            'Schiller',
            'Post',
            'Poststraße',
            'Wall',
            'Turm',
            'Neue',
            'Lange',
            'Breite',
            'Hohe',
            'Wasser',
            'Salz',
            'Burg',
            'Rathaus',
            'Friedhof',
            'Fabrik',
            'Hafen',
          ],
          feature: [
            'Markt',
            'Rathaus',
            'Stadttor',
            'Mühlgraben',
            'Bahndamm',
            'Schlossgarten',
            'Anger',
            'Zollhaus',
            'Alten Friedhof',
            'Kalkofen',
          ],
          feature2: ['Stadtmauer', 'Kirche', 'Post', 'Schleuse', 'Brauerei', 'Bleiche', 'Alten Mühle'],
          saint: ['Sankt-Georg', 'Sankt-Nikolai', 'Sankt-Marien', 'Sankt-Jakobs'],
        },
      },
      streetSuffix: {
        artery: ['straße', 'allee', 'ring'],
        road: ['straße', 'chaussee', 'weg'],
        collector: ['straße', 'straße', 'allee'],
        street: ['straße', 'gasse', 'weg', 'platz'],
        lane: ['gasse', 'gässchen', 'hof', 'steig', 'winkel'],
      },
      district: {
        patterns: ['{feature}viertel', '{dir}stadt', '{name}vorstadt', 'Am {feature2}', '{family}siedlung'],
        parts: {
          dir: ['Nord', 'Süd', 'Ost', 'West', 'Alt', 'Neu', 'Ober', 'Unter'],
          feature: [
            'Bahnhofs',
            'Dom',
            'Gründer',
            'Garten',
            'Hafen',
            'Fabrik',
            'Schloss',
            'Kloster',
            'Wall',
            'Mühlen',
            'Tuch',
            'Gerber',
          ],
          name: ['Kirch', 'Mühl', 'Salz', 'Berg', 'Tor', 'Brücken'],
          feature2: ['Hang', 'Bahndamm', 'Anger', 'Wasserturm', 'Schützenhaus', 'Exerzierplatz'],
        },
      },
      water: {
        patterns: ['Die {name}', 'Der {name2}', '{name3}bach'],
        parts: {
          name: ['Ilm', 'Werra', 'Saale', 'Lahn', 'Wupper', 'Nidda', 'Wied'],
          name2: ['Mühlbach', 'Sülzbach', 'Kocher', 'Neckar', 'Lech'],
          name3: ['Mühl', 'Kalt', 'Rot', 'Krebs', 'Schwarz', 'Silber'],
        },
      },
      business: {
        patterns: [
          '{family} & Söhne',
          '{trade} {family}',
          'Gasthaus zum {adj} {noun}',
          '{family} {trade} GmbH',
          'Gebrüder {family}',
          'Hotel {noun}',
        ],
        parts: {
          adj: ['Goldenen', 'Weißen', 'Schwarzen', 'Grünen', 'Roten', 'Alten'],
          noun: ['Löwen', 'Adler', 'Hirsch', 'Bären', 'Ochsen', 'Ross', 'Anker', 'Krone', 'Stern', 'Post'],
        },
      },
      quarters: {
        core: 'Altstadt',
        cathedral: 'Domviertel',
        castle: 'Burgviertel',
        market: 'Am Markt',
        port: 'Hafenviertel',
        fishing: 'Fischerviertel',
        industrial: 'Fabrikviertel',
        station: 'Bahnhofsviertel',
      },
    },
    conventions: {
      earlyPattern: 'organic',
      modernFrom: 1850,
      blockSizeScale: 1,
      streetcarReach: 0.8,
      buildingKinds: {
        house: 'Fachwerkhaus',
        townhouse: 'Bürgerhaus',
        mansion: 'Villa',
        shophouse: 'Geschäftshaus',
        shack: 'Hinterhaus',
        keep: 'Bergfried',
        cathedral: 'Dom',
        rowhouse: 'Reihenhaus',
        tenement: 'Mietskaserne',
        shop: 'Laden',
        office: 'Bürohaus',
        villa: 'Villa',
        apartment: 'Wohnblock',
        tower: 'Hochhaus',
        warehouse: 'Lagerhaus',
        workshop: 'Werkstatt',
      },
      religious: ['evangelische Kirche', 'katholische Kirche', 'Klosterkirche', 'Synagoge', 'Kapelle'],
      civic: [
        'Rathaus',
        'Amtsgericht',
        'Postamt',
        'Volksschule',
        'Gymnasium',
        'Feuerwache',
        'Sparkasse',
        'Schützenhaus',
        'Krankenhaus',
      ],
      materials: {
        preIndustrial: { timber: 6, stone: 4, brick: 2 },
        industrial: { brick: 6, stone: 4, timber: 2 },
        modern: { brick: 3, concrete: 5, stone: 2, steel: 1 },
      },
      transport: { rail: 1838, tram: 1881, motorway: 1935, container: 1968 },
      walls: true,
    },
  },
  {
    id: 'iberia',
    name: 'Iberia',
    description: 'Plaza mayor grids, Moorish old towns, Atlantic and Mediterranean ports.',
    language: 'es',
    naming: {
      given: [
        'Antonio',
        'Manuel',
        'José',
        'Francisco',
        'Juan',
        'Rafael',
        'Joaquín',
        'Ramón',
        'María',
        'Carmen',
        'Dolores',
        'Pilar',
        'Rosario',
        'Concepción',
        'Teresa',
        'Isabel',
        'Enrique',
        'Miguel',
        'Luis',
        'Fernando',
        'Ana',
        'Josefa',
        'Mercedes',
        'Inés',
      ],
      family: [
        'García',
        'Fernández',
        'López',
        'Martínez',
        'Sánchez',
        'Romero',
        'Navarro',
        'Torres',
        'Ruiz',
        'Jiménez',
        'Moreno',
        'Álvarez',
        'Serrano',
        'Blanco',
        'Molina',
        'Ortega',
        'Delgado',
        'Castro',
        'Vargas',
        'Iglesias',
        'Medina',
        'Herrera',
        'Peña',
        'Cortés',
        'Guerrero',
        'Salazar',
        'Vidal',
        'Carrasco',
        'Ferreira',
        'Almeida',
      ],
      settlement: {
        patterns: [
          '{root}{suffix}',
          'Villa{root2}',
          'San {saint}',
          'Puerto {de} {noun}',
          'Santa {saint2} de {noun}',
        ],
        parts: {
          root: [
            'Alca',
            'Val',
            'Tor',
            'Mon',
            'Alma',
            'Cala',
            'Vila',
            'Ponte',
            'Casti',
            'Medina',
            'Guada',
            'Bena',
            'Alba',
            'Ribe',
            'Santi',
          ],
          suffix: [
            'lar',
            'verde',
            'real',
            'del Río',
            'de la Sierra',
            'nueva',
            'franca',
            'mar',
            'fría',
            'llana',
            'roque',
            'cázar',
          ],
          root2: ['nueva', 'franca', 'real', 'garcía', 'hermosa', 'blanca'],
          saint: ['Sebastián', 'Fernando', 'Vicente', 'Lorenzo', 'Esteban', 'Martín', 'Roque'],
          saint2: ['Cruz', 'Marta', 'Ana', 'Eulalia', 'Clara'],
          de: ['de', 'del', 'de la'],
          noun: ['Mar', 'Ribera', 'Faro', 'Sierra', 'Palma', 'Sal', 'Oro', 'Norte', 'Rey'],
        },
      },
      street: {
        patterns: [
          'Calle {de} {name}',
          'Calle {family}',
          '{suffix} {de} {name}',
          'Plaza {de} {name}',
          'Calle de {saint}',
          'Callejón {de} {feature}',
        ],
        parts: {
          de: ['de', 'del', 'de la', 'de los'],
          name: [
            'Mayor',
            'Real',
            'Nueva',
            'Ancha',
            'Sol',
            'Luna',
            'Reyes Católicos',
            'Constitución',
            'Libertad',
            'Cervantes',
            'Colón',
            'Mercado',
            'Iglesia',
            'Muralla',
            'Alcázar',
            'Puerto',
            'Estación',
            'Ferrocarril',
            'Fuente',
            'Cruz',
            'Carmen',
            'Rosario',
            'Ánimas',
            'Toro',
            'Barca',
            'Herrería',
            'Jardines',
          ],
          saint: [
            'San Juan',
            'San Pedro',
            'San Miguel',
            'Santa María',
            'San Antón',
            'Santa Lucía',
            'San Isidro',
          ],
          feature: ['Gato', 'Agua', 'Silencio', 'Beso', 'Perro', 'Horno', 'Pozo', 'Cuesta'],
        },
      },
      streetSuffix: {
        artery: ['Avenida', 'Paseo', 'Gran Vía'],
        road: ['Carretera', 'Camino', 'Avenida'],
        collector: ['Calle', 'Avenida', 'Ronda'],
        street: ['Calle', 'Calle', 'Plaza', 'Travesía'],
        lane: ['Callejón', 'Pasaje', 'Cuesta', 'Adarve'],
      },
      district: {
        patterns: [
          'Barrio {de} {feature}',
          'El {feature}',
          'La {feature2}',
          'Barrio de {saint}',
          '{feature3}',
        ],
        parts: {
          de: ['de', 'del', 'de la', 'de los'],
          feature: [
            'Arrabal',
            'Mercado',
            'Puerto',
            'Catedral',
            'Alcázar',
            'Judería',
            'Morería',
            'Ensanche',
            'Estación',
            'Pescadores',
            'Curtidores',
            'Tejedores',
          ],
          feature2: ['Ribera', 'Marina', 'Judería', 'Alameda', 'Magdalena', 'Victoria', 'Albaicín', 'Triana'],
          saint: ['San Juan', 'San Pedro', 'Santa Cruz', 'San Roque', 'San Lázaro'],
          feature3: ['El Arrabal', 'La Marina', 'El Ensanche', 'Las Delicias', 'Los Remedios'],
        },
      },
      water: {
        patterns: ['Río {name}', 'Arroyo {de} {name2}', 'Ría de {name3}'],
        parts: {
          name: ['Guadalete', 'Alberche', 'Nalón', 'Odiel', 'Turia', 'Segre', 'Zújar', 'Mondego'],
          de: ['de', 'del', 'de la'],
          name2: ['Molino', 'Fuente', 'Cañas', 'Piedra', 'Salado'],
          name3: ['Arosa', 'Vigo', 'Ferrol', 'Aveiro'],
        },
      },
      business: {
        patterns: [
          'Casa {family}',
          '{family} e Hijos',
          'Bodega {family}',
          'Almacenes {family}',
          'Bar {noun}',
          'Fonda {de} {noun}',
          '{trade} {family}',
        ],
        parts: {
          de: ['de', 'del', 'de la'],
          noun: [
            'Sol',
            'Luna',
            'Comercio',
            'Puerto',
            'Estrella',
            'Paz',
            'Universo',
            'Central',
            'Ideal',
            'Español',
          ],
        },
      },
      quarters: {
        core: 'Casco Antiguo',
        cathedral: 'Barrio de la Catedral',
        castle: 'Barrio del Alcázar',
        market: 'Plaza Mayor',
        port: 'La Marina',
        fishing: 'Barrio de Pescadores',
        industrial: 'Polígono',
        station: 'Barrio de la Estación',
      },
    },
    conventions: {
      earlyPattern: 'organic',
      modernFrom: 1860,
      blockSizeScale: 0.9,
      streetcarReach: 0.6,
      buildingKinds: {
        house: 'casa de patio',
        townhouse: 'casa señorial',
        mansion: 'palacio',
        shophouse: 'casa con tienda',
        shack: 'chabola',
        keep: 'torre del homenaje',
        cathedral: 'catedral',
        rowhouse: 'casa adosada',
        tenement: 'corrala',
        shop: 'tienda',
        office: 'edificio de oficinas',
        villa: 'chalet',
        apartment: 'bloque de pisos',
        tower: 'torre',
        warehouse: 'almacén',
        workshop: 'taller',
      },
      religious: ['iglesia parroquial', 'ermita', 'convento', 'capilla', 'colegiata'],
      civic: [
        'ayuntamiento',
        'lonja',
        'mercado de abastos',
        'cuartel de la Guardia Civil',
        'casa de correos',
        'escuela',
        'juzgado',
        'casino',
        'plaza de toros',
      ],
      materials: {
        preIndustrial: { stone: 5, adobe: 3, brick: 2, timber: 1 },
        industrial: { brick: 5, stone: 4, adobe: 1 },
        modern: { brick: 4, concrete: 5, stone: 1 },
      },
      transport: { rail: 1848, tram: 1899, motorway: 1969, container: 1972 },
      walls: true,
    },
  },
  {
    id: 'egyptLevant',
    name: 'Egypt and the Levant',
    description: 'Medinas, khans and colonial-era quarters on the Nile and the Levantine coast.',
    language: 'ar',
    naming: {
      given: [
        'Ahmad',
        'Mahmoud',
        'Youssef',
        'Ibrahim',
        'Mustafa',
        'Hassan',
        'Karim',
        'Omar',
        'Fatima',
        'Aisha',
        'Zaynab',
        'Layla',
        'Nour',
        'Samira',
        'Huda',
        'Mariam',
        'Khalil',
        'Salim',
        'Tawfiq',
        'Nabil',
        'Amina',
        'Rania',
        'Yasmin',
        'Dalia',
      ],
      family: [
        'Haddad',
        'Khoury',
        'Saleh',
        'Mansour',
        'Nasser',
        'Farouk',
        'Abdallah',
        'Sayed',
        'Rizk',
        'Ghali',
        'Shehata',
        'Tantawi',
        'Qasim',
        'Bishara',
        'Zaki',
        'Mubarak',
        'Hamdi',
        'Najjar',
        'Sabbagh',
        'Awad',
        'Fahmy',
        'Nassar',
        'Boutros',
        'Sarraf',
        'Halabi',
        'Maalouf',
        'Ayoub',
        'Dahdah',
        'Shamoun',
        'Ezzat',
      ],
      settlement: {
        patterns: [
          '{prefix} {root}',
          'Bani {family}',
          '{root}{suffix}',
          'Kafr {root2}',
          'Tell {root2}',
          'Minyat {root2}',
        ],
        parts: {
          prefix: ['Al-', 'Beit ', 'Deir ', 'Ras ', 'Ain ', 'Wadi ', 'Bab ', 'Mit '],
          root: [
            'Hamra',
            'Qadima',
            'Manzala',
            'Bahri',
            'Salam',
            'Zahra',
            'Karnak',
            'Rashid',
            'Suwayda',
            'Nabq',
            'Fayum',
            'Aziziya',
            'Mansura',
            'Qusayr',
          ],
          suffix: ['iya', 'iyah', 'a', 'eh'],
          root2: ['el-Sheikh', 'Hamad', 'Nasr', 'Saleh', 'Zayat', 'el-Dawwar', 'Abu Zeid', 'Ghanem'],
        },
      },
      street: {
        patterns: [
          '{suffix} {name}',
          '{suffix} {family}',
          '{suffix} al-{feature}',
          '{suffix} {saint}',
          'Haret {family}',
        ],
        parts: {
          name: [
            'al-Nil',
            'al-Azhar',
            'Qasr al-Nil',
            'al-Muizz',
            'al-Gumhuriya',
            'Ramses',
            'Salah Salem',
            'al-Tahrir',
            'al-Bahr',
            'al-Mahatta',
            'al-Suq',
            'al-Qala’a',
            'Bab al-Wazir',
            'al-Manshiya',
            'Abu Qir',
            'al-Hurriya',
            'al-Istiqlal',
            'al-Nasr',
            'al-Mina',
            'al-Hamidiyya',
            'al-Salihiyya',
          ],
          feature: [
            'Suq',
            'Qala’a',
            'Jami’',
            'Khan',
            'Hammam',
            'Madrasa',
            'Sabil',
            'Wikala',
            'Bab',
            'Mina',
            'Sikka al-Hadid',
            'Bustan',
            'Maqbara',
            'Saqiya',
          ],
          saint: ['Sayyida Zaynab', 'al-Hussein', 'Sitt Nafisa', 'Mar Girgis', 'Abu Sefein', 'Sheikh Rihan'],
        },
      },
      streetSuffix: {
        artery: ['Sharia', 'Corniche', 'Sharia'],
        road: ['Tariq', 'Sharia', 'Sikka'],
        collector: ['Sharia', 'Sharia', 'Darb'],
        street: ['Sharia', 'Darb', 'Haret', 'Zuqaq'],
        lane: ['Zuqaq', 'Atfet', 'Haret', 'Sikka'],
      },
      district: {
        patterns: [
          'Hayy al-{feature}',
          'Harat al-{feature}',
          'Bab al-{feature}',
          'al-{feature2}',
          'Darb al-{feature}',
        ],
        parts: {
          feature: [
            'Yahud',
            'Nasara',
            'Sagha',
            'Khiyamiya',
            'Nahhasin',
            'Hattabin',
            'Ghuriya',
            'Muski',
            'Attarin',
            'Suq',
            'Qala’a',
            'Mina',
            'Bahriya',
            'Zahra',
            'Mahatta',
          ],
          feature2: [
            'Manshiya',
            'Azbakiya',
            'Gamaliya',
            'Ataba',
            'Zamalek',
            'Garden City',
            'Hamra',
            'Ashrafiya',
            'Salihiya',
            'Midan',
          ],
        },
      },
      water: {
        patterns: ['Bahr {name}', 'Tir’at al-{name2}', 'Wadi {name3}', 'Nahr al-{name2}'],
        parts: {
          name: ['Yusuf', 'Shibin', 'Muweis', 'Saghir', 'Nasiri'],
          name2: ['Ismailiya', 'Mahmudiya', 'Nubariya', 'Bahriya', 'Awali', 'Kalb'],
          name3: ['Natrun', 'Rayan', 'Musa', 'Hof', 'Qena'],
        },
      },
      business: {
        patterns: [
          '{family} {trade}',
          'Wikalat {family}',
          'Qahwat al-{noun}',
          'Mahal {family} lil-{trade}',
          'Khan al-{noun}',
          '{trade} Abu {given}',
        ],
        parts: {
          noun: ['Fishawi', 'Nil', 'Bustan', 'Hurriya', 'Sultan', 'Gamil', 'Khalili', 'Salam', 'Amir'],
        },
      },
      quarters: {
        core: 'al-Madina al-Qadima',
        cathedral: 'Hayy al-Jami’ al-Kabir',
        castle: 'Hayy al-Qala’a',
        market: 'al-Suq',
        port: 'al-Mina',
        fishing: 'Hayy al-Sayyadin',
        industrial: 'al-Masani’',
        station: 'al-Mahatta',
      },
    },
    conventions: {
      earlyPattern: 'organic',
      modernFrom: 1880,
      blockSizeScale: 0.7,
      streetcarReach: 0.3,
      buildingKinds: {
        house: 'courtyard house',
        townhouse: 'bayt with mashrabiya',
        mansion: 'saray',
        shophouse: 'dukkan with rooms above',
        shack: 'mud-brick house',
        keep: 'citadel',
        cathedral: 'great mosque',
        rowhouse: 'rab’ tenement',
        tenement: 'rab’',
        shop: 'dukkan',
        office: 'commercial building',
        villa: 'villa',
        apartment: 'apartment block',
        tower: 'tower',
        warehouse: 'wikala',
        workshop: 'workshop',
      },
      religious: [
        'mosque',
        'zawiya',
        'Coptic church',
        'synagogue',
        'madrasa',
        'Greek Orthodox church',
        'Maronite church',
      ],
      civic: [
        'khan',
        'hammam',
        'sabil-kuttab',
        'wikala',
        'mudiriya',
        'police post',
        'telegraph office',
        'customs house',
        'cotton exchange',
      ],
      materials: {
        preIndustrial: { mudbrick: 6, stone: 4, timber: 1 },
        industrial: { stone: 5, brick: 3, mudbrick: 3 },
        modern: { concrete: 6, brick: 3, stone: 2 },
      },
      transport: { rail: 1854, tram: 1896, motorway: 1980, container: 1985 },
      walls: true,
    },
    colonial: { culture: 'england', from: 1882, to: 1956, share: 0.3 },
  },
  {
    id: 'china',
    name: 'China',
    description: 'Walled prefectural cities, treaty-port bunds and hutong lanes.',
    language: 'zh',
    naming: {
      given: [
        'Wei',
        'Ming',
        'Jun',
        'Hua',
        'Lan',
        'Mei',
        'Ling',
        'Yun',
        'Bao',
        'Xiu',
        'Guo',
        'Liang',
        'Fang',
        'Qing',
        'Zhen',
        'Hong',
        'Feng',
        'Rui',
        'Shu',
        'Yan',
        'Bo',
        'Kai',
        'Ping',
        'Zhi',
      ],
      family: [
        'Wang',
        'Li',
        'Zhang',
        'Liu',
        'Chen',
        'Yang',
        'Huang',
        'Zhao',
        'Wu',
        'Zhou',
        'Xu',
        'Sun',
        'Ma',
        'Zhu',
        'Hu',
        'Guo',
        'Lin',
        'He',
        'Gao',
        'Luo',
        'Zheng',
        'Liang',
        'Xie',
        'Song',
        'Tang',
        'Han',
        'Feng',
        'Deng',
        'Cao',
        'Peng',
      ],
      settlement: {
        patterns: ['{root}{suffix}', '{root}{root2}', '{dir}{root}', '{root}{water}'],
        parts: {
          root: [
            'An',
            'Chang',
            'Ning',
            'Ping',
            'Tai',
            'Fu',
            'Xin',
            'Yong',
            'Jin',
            'Hai',
            'Jiang',
            'Lin',
            'Qing',
            'Shun',
            'Tong',
            'Wen',
            'Xiang',
            'Yuan',
            'Zhen',
            'Gu',
          ],
          root2: ['zhou', 'an', 'shan', 'ling', 'he', 'kou', 'ping', 'cheng', 'yang', 'yuan', 'tai'],
          suffix: ['zhou', 'cheng', 'zhen', 'xian', 'kou', 'pu', 'guan', 'ji', 'tun', 'wan'],
          dir: ['Bei', 'Nan', 'Dong', 'Xi', 'Zhong'],
          water: ['jiang', 'he', 'hu', 'kou', 'wan'],
        },
      },
      street: {
        patterns: ['{name} {suffix}', '{dir}{name} {suffix}', '{family}jia {suffix}', '{trade} {suffix}'],
        parts: {
          name: [
            'Zhongshan',
            'Renmin',
            'Jiefang',
            'Heping',
            'Nanjing',
            'Beijing',
            'Fuxing',
            'Xinhua',
            'Wenhua',
            'Jianguo',
            'Huancheng',
            'Guanqian',
            'Chengmen',
            'Gulou',
            'Zhonghua',
            'Yan’an',
            'Shengli',
            'Guangming',
            'Tuanjie',
            'Minsheng',
            'Chaoyang',
            'Xingfu',
          ],
          dir: ['Dong', 'Xi', 'Nan', 'Bei', 'Zhong'],
          trade: [
            'Zhujiang',
            'Caishi',
            'Miliang',
            'Youzha',
            'Tieqi',
            'Buxie',
            'Chahang',
            'Yanghang',
            'Shuguo',
            'Huacai',
          ],
        },
      },
      streetSuffix: {
        artery: ['Dajie', 'Dadao', 'Lu'],
        road: ['Lu', 'Gonglu', 'Dadao'],
        collector: ['Lu', 'Jie', 'Dajie'],
        street: ['Jie', 'Lu', 'Xiang'],
        lane: ['Hutong', 'Xiang', 'Nong', 'Li', 'Long'],
      },
      district: {
        patterns: ['{dir}guan', '{feature}fang', '{feature}qiao', '{name}li', '{dir}cheng'],
        parts: {
          dir: ['Dong', 'Xi', 'Nan', 'Bei', 'Zhong'],
          feature: [
            'Wenmiao',
            'Gulou',
            'Chenghuang',
            'Chengmen',
            'Xinshi',
            'Shuitou',
            'Matou',
            'Caoshi',
            'Shiqiao',
            'Huayuan',
            'Shuyuan',
            'Yanhang',
          ],
          name: [
            'Fuxing',
            'Anle',
            'Taiping',
            'Tongfu',
            'Yongkang',
            'Changshou',
            'Jixiang',
            'Ruyi',
            'Qingyun',
            'Baoshan',
          ],
        },
      },
      water: {
        patterns: ['{name} Jiang', '{name} He', '{name} Xi', '{name} Hu'],
        parts: {
          name: [
            'Qing',
            'Jin',
            'Bai',
            'Lian',
            'Xin’an',
            'Tuo',
            'Yu',
            'Qiantang',
            'Han',
            'Xiang',
            'Long',
            'Yong',
          ],
        },
      },
      business: {
        patterns: [
          '{family}ji {trade}',
          '{adj}{adj2} {trade}',
          '{family} Family {trade}',
          '{adj}{adj2}lou',
          '{adj}{adj2} Hao',
        ],
        parts: {
          adj: ['Tong', 'Fu', 'Rui', 'De', 'Yong', 'Xin', 'Da', 'Heng', 'Yi', 'Chang'],
          adj2: ['sheng', 'xing', 'fu', 'chang', 'tai', 'he', 'yuan', 'long', 'ji', 'kang'],
        },
      },
      quarters: {
        core: 'Old Walled City',
        cathedral: 'Temple Quarter',
        castle: 'Yamen Quarter',
        market: 'Market Ward',
        port: 'The Bund',
        fishing: 'Fishermen’s Lane',
        industrial: 'Workshops Ward',
        station: 'Station Ward',
      },
    },
    conventions: {
      earlyPattern: 'grid',
      modernFrom: 1780,
      blockSizeScale: 0.85,
      streetcarReach: 0.5,
      buildingKinds: {
        house: 'siheyuan courtyard house',
        townhouse: 'merchant compound',
        mansion: 'garden mansion',
        shophouse: 'shophouse',
        shack: 'lean-to',
        keep: 'yamen',
        cathedral: 'Confucian temple',
        rowhouse: 'shikumen row',
        tenement: 'lilong tenement',
        shop: 'shophouse',
        office: 'trading house',
        villa: 'garden villa',
        apartment: 'apartment block',
        tower: 'tower',
        warehouse: 'godown',
        workshop: 'workshop',
      },
      religious: [
        'Buddhist temple',
        'Daoist temple',
        'City God temple',
        'ancestral hall',
        'mosque',
        'Christian mission church',
      ],
      civic: [
        'yamen',
        'drum tower',
        'bell tower',
        'academy',
        'guild hall',
        'examination hall',
        'granary',
        'telegraph office',
        'customs house',
      ],
      materials: {
        preIndustrial: { timber: 6, brick: 4, stone: 1, rammedEarth: 3 },
        industrial: { brick: 6, timber: 4, stone: 1 },
        modern: { concrete: 6, brick: 3, steel: 1 },
      },
      transport: { rail: 1876, tram: 1906, motorway: 1988, container: 1978 },
      walls: true,
    },
    colonial: { culture: 'england', from: 1842, to: 1943, share: 0.25 },
  },
  {
    id: 'japan',
    name: 'Japan',
    description: 'Castle towns, post towns and Meiji treaty ports.',
    language: 'ja',
    naming: {
      given: [
        'Hiroshi',
        'Takeshi',
        'Kenji',
        'Ichiro',
        'Shigeru',
        'Tadashi',
        'Isamu',
        'Yoshio',
        'Haru',
        'Kiyo',
        'Fumi',
        'Toshi',
        'Sachiko',
        'Yoshiko',
        'Chiyo',
        'Masako',
        'Goro',
        'Saburo',
        'Kazuo',
        'Minoru',
        'Hana',
        'Ume',
        'Tomi',
        'Kimi',
      ],
      family: [
        'Sato',
        'Suzuki',
        'Takahashi',
        'Tanaka',
        'Watanabe',
        'Ito',
        'Yamamoto',
        'Nakamura',
        'Kobayashi',
        'Kato',
        'Yoshida',
        'Yamada',
        'Sasaki',
        'Yamaguchi',
        'Matsumoto',
        'Inoue',
        'Kimura',
        'Hayashi',
        'Shimizu',
        'Yamazaki',
        'Mori',
        'Abe',
        'Ikeda',
        'Hashimoto',
        'Ishikawa',
        'Ogawa',
        'Maeda',
        'Fujita',
        'Okada',
        'Goto',
      ],
      settlement: {
        patterns: ['{root}{suffix}', '{root}{root2}', '{dir}{root}'],
        parts: {
          root: [
            'Kawa',
            'Yama',
            'Naka',
            'Oo',
            'Shin',
            'Fuku',
            'Matsu',
            'Take',
            'Nishi',
            'Higashi',
            'Kita',
            'Minami',
            'Ishi',
            'Hoso',
            'Kuro',
            'Shira',
            'Kuma',
            'Tsu',
            'Naga',
            'Iwa',
          ],
          suffix: [
            'saki',
            'shima',
            'zaki',
            'moto',
            'hama',
            'kawa',
            'oka',
            'mura',
            'machi',
            'zawa',
            'minato',
            'ura',
            'gata',
            'no',
            'ya',
          ],
          root2: ['saki', 'moto', 'hara', 'da', 'no', 'ta', 'guchi'],
          dir: ['Kita', 'Minami', 'Higashi', 'Nishi', 'Naka'],
        },
      },
      street: {
        patterns: ['{name}{suffix}', '{name}-{suffix}', '{trade}{suffix}', '{number}chome-{suffix}'],
        parts: {
          name: [
            'Hon',
            'Eki-mae',
            'Shin',
            'Naka',
            'Otemachi',
            'Sakura',
            'Minato',
            'Kaigan',
            'Uomachi',
            'Kajiya',
            'Teramachi',
            'Yanagi',
            'Suehiro',
            'Ginza',
            'Motomachi',
            'Hama',
            'Nakano',
            'Daimyo',
            'Bakuro',
            'Nishiki',
          ],
          trade: ['Kaji', 'Konya', 'Daiku', 'Uo', 'Kome', 'Sakana', 'Kome', 'Shio', 'Kawara', 'Yumi'],
          number: ['Ichi', 'Ni', 'San', 'Yon', 'Go', 'Roku'],
        },
      },
      streetSuffix: {
        artery: ['dori', 'kaido', 'odori'],
        road: ['kaido', 'dori', 'michi'],
        collector: ['dori', 'dori', 'suji'],
        street: ['machi', 'cho', 'dori'],
        lane: ['yokocho', 'koji', 'roji', 'suji'],
      },
      district: {
        patterns: ['{name}machi', '{name}cho', '{dir}-ku', '{trade}machi', '{name}dai'],
        parts: {
          name: [
            'Hon',
            'Sakura',
            'Ume',
            'Naka',
            'Shin',
            'Motomachi',
            'Kaigan',
            'Teramachi',
            'Shiro',
            'Yanagi',
            'Tsukiji',
            'Marunouchi',
            'Ura',
            'Hama',
          ],
          dir: ['Kita', 'Minami', 'Higashi', 'Nishi', 'Chuo'],
          trade: ['Kaji', 'Konya', 'Daiku', 'Uo', 'Kome', 'Sakana', 'Kawara', 'Zaimoku'],
        },
      },
      water: {
        patterns: ['{name}gawa', '{name}kawa', '{name}numa', '{name} Bay'],
        parts: {
          name: [
            'Kuro',
            'Shira',
            'Naka',
            'Oo',
            'Naga',
            'Kita',
            'Tama',
            'Kiso',
            'Yodo',
            'Sumida',
            'Shinano',
            'Kamo',
          ],
        },
      },
      business: {
        patterns: [
          '{family}ya',
          '{family} Shoten',
          '{noun}ya',
          '{family} {trade}',
          '{noun}-do',
          '{family} Gumi',
        ],
        parts: {
          noun: [
            'Matsu',
            'Take',
            'Ume',
            'Tsuru',
            'Kame',
            'Fuji',
            'Sakura',
            'Kiku',
            'Tsuki',
            'Hoshi',
            'Daikoku',
            'Ebisu',
          ],
        },
      },
      quarters: {
        core: 'Jokamachi',
        cathedral: 'Teramachi',
        castle: 'Shiro',
        market: 'Ichiba',
        port: 'Minato',
        fishing: 'Gyoson',
        industrial: 'Kojo-chitai',
        station: 'Ekimae',
      },
    },
    conventions: {
      earlyPattern: 'grid',
      modernFrom: 1780,
      blockSizeScale: 0.8,
      streetcarReach: 0.9,
      buildingKinds: {
        house: 'machiya',
        townhouse: 'buke-yashiki',
        mansion: 'daimyo residence',
        shophouse: 'machiya shop',
        shack: 'nagaya',
        keep: 'tenshu',
        cathedral: 'temple',
        rowhouse: 'nagaya row',
        tenement: 'nagaya',
        shop: 'shop-house',
        office: 'office building',
        villa: 'detached house',
        apartment: 'danchi block',
        tower: 'tower mansion',
        warehouse: 'kura storehouse',
        workshop: 'workshop',
      },
      religious: ['Shinto shrine', 'Buddhist temple', 'Zen temple', 'Inari shrine', 'Christian church'],
      civic: [
        'town hall',
        'police box',
        'post office',
        'public bath',
        'school',
        'kabuki theatre',
        'fire watchtower',
        'prefectural office',
      ],
      materials: {
        preIndustrial: { timber: 9, stone: 1, earth: 2 },
        industrial: { timber: 7, brick: 3, stone: 1 },
        modern: { concrete: 6, timber: 3, steel: 2 },
      },
      transport: { rail: 1872, tram: 1895, motorway: 1963, container: 1967 },
      walls: false,
    },
  },
];

export const CULTURE_PACKS: CulturePack[] = raw.map((p) => culturePackSchema.parse(p));

// Packs a document carries with it (plugins); they take precedence over the built-ins by id.
let extraPacks: CulturePack[] = [];

/** Register document-level culture packs for this engine run (replaces the previous set). */
export function registerCulturePacks(packs: readonly CulturePack[]): void {
  extraPacks = packs.map((p) => culturePackSchema.parse(p));
}

/** Every pack available now: registered plugins first, then the built-ins. */
export function allCulturePacks(): CulturePack[] {
  return [...extraPacks, ...CULTURE_PACKS.filter((b) => !extraPacks.some((e) => e.id === b.id))];
}

export function culturePack(id: string | undefined): CulturePack {
  return extraPacks.find((p) => p.id === id) ?? CULTURE_PACKS.find((p) => p.id === id) ?? CULTURE_PACKS[0]!;
}

export function culturePackById(id: string): CulturePack | undefined {
  return extraPacks.find((p) => p.id === id) ?? CULTURE_PACKS.find((p) => p.id === id);
}
